/*************************************************************************************************/
-- ENTERPRISE CLEARING & SETTLEMENT DATA PLATFORM TEARDOWN
-- Version: 1.0
--
-- WARNING: This script will permanently delete all solution data.
-- The shared SF_SOLUTIONS database and SF_SOLUTIONS_WH warehouse are NOT dropped.
/*************************************************************************************************/

USE ROLE ACCOUNTADMIN;

DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_CONSUMPTION.ENTERPRISE_DAILY_DASHBOARD;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_CONSUMPTION.ENTERPRISE_PARTICIPANT_RISK_MONITOR;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_NORMALIZED.BUSINESS_RULES_ENGINE;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_NORMALIZED.REFERENCE_ENRICHMENT;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_NORMALIZED.SETTLEMENT_VALIDATION;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_DQ.SETTLEMENT_TRANSACTIONS_CLEANSED;
DROP DYNAMIC TABLE IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_DQ.SETTLEMENT_QUALITY_METRICS;

DROP SCHEMA IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_CONSUMPTION;
DROP SCHEMA IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_NORMALIZED;
DROP SCHEMA IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_DQ;
DROP SCHEMA IF EXISTS SF_SOLUTIONS.CLEARING_SETTLEMENT_RAW;

DROP WAREHOUSE IF EXISTS SF_SOLUTIONS_ETL_WH;
DROP WAREHOUSE IF EXISTS SF_SOLUTIONS_ANALYTICS_WH;

SELECT 'Enterprise Clearing & Settlement teardown complete.' as STATUS;
